export const newWords = {
  I: "Je",
  love: "aime",
  learning: "apprendre",
  languages: "les langues",
  language: "la langue",
  premier: "premier",
  cinq: "ssss",
};

const newWord = [
  {
    id: 1,
    word: "Défendre",
    definition: "ci, interdit, qui n’est pas permis.",
    translation: "to defend",
  },
  {
    id: 2,
    word: "Une Hotellerie",
    definition: "maison où on loue des chambres.",
    translation: "a hotel",
  },
  {
    id: 3,
    word: "Pendre",
    definition: "ici, descendre.",
    translation: "to hang",
  },
  {
    id: 4,
    word: "La chance",
    definition: "quelque chose de bien qui nous arrive.",
    translation: "luck",
  },
  {
    id: 5,
    word: "Les difficultés",
    definition: "les choses difficiles, les problèmes.",
    translation: "difficulties",
  },
  {
    id: 6,
    word: "Donner un conseil",
    definition: "dire à quelqu'un ce qu'on pense qu'il doit faire.",
    translation: "to give advice",
  },
  {
    id: 7,
    word: "Un médicament",
    definition: "ça sert à guérir quand on est malade ou blessé.",
    translation: "a medicine",
  },
  {
    id: 8,
    word: "Nour",
    definition: "Nour definition goes here.",
    translation: "",
  },
  {
    id: 9,
    word: "Guérir",
    definition: "rendre la santé.",
    translation: "to heal",
  },
  {
    id: 10,
    word: "Insulter (quelqu'un)",
    definition: "lui dire des choses désagréables, des injures.",
    translation: "to insult (someone)",
  },
  {
    id: 11,
    word: "Écouter avec attention",
    definition: "écouter en essayant de bien retenir.",
    translation: "to listen carefully",
  },
  {
    id: 12,
    word: "Se tromper",
    definition: "ici, croire une chose fausse.",
    translation: "to make a mistake",
  },
  {
    id: 13,
    word: "Fort",
    definition: "ici, gros.",
    translation: "strong",
  },
  {
    id: 14,
    word: "Faire une remarque",
    definition: "ici, dire quelque chose de désagréable.",
    translation: "to make a remark",
  },
  {
    id: 15,
    word: "La colère monte en lui",
    definition: "il devient de plus en plus fâché.",
    translation: "the anger rises within him",
  },
  {
    id: 16,
    word: "Une parole",
    definition: "un mot.",
    translation: "a word",
  },
  {
    id: 17,
    word: "Sortir l'épée du fourreau",
    definition: "sortir l'épée de son étui.",
    translation: "to draw the sword from its sheath",
  },
  {
    id: 18,
    word: "Faire semblant",
    definition: "essayer de faire croire quelque chose de faux.",
    translation: "to pretend",
  },
  {
    id: 19,
    word: "Un bouton d'or",
    definition:
      "une petite fleur jaune qui pousse dans les prairies de France.",
    translation: "a buttercup",
  },
  {
    id: 20,
    word: "Tenir à",
    definition: "vouloir vraiment faire cette chose.",
    translation: "to care about",
  },
  {
    id: 21,
    word: "Se moquer de quelqu'un",
    definition: "rire de lui.",
    translation: "to make fun of someone",
  },
  {
    id: 22,
    word: "À mi-voix",
    definition: "à voix basse.",
    translation: "in a low voice",
  },
  {
    id: 23,
    word: "Saluer",
    definition: "avant de se battre, les nobles se saluent.",
    translation: "to greet",
  },
  {
    id: 24,
    word: "Se mettre en garde",
    definition: "placer l'épée devant soi pour se préparer à se battre.",
    translation: "to prepare oneself for a fight",
  },
  {
    id: 25,
    word: "L'hôtelier",
    definition: "le patron de l'hôtellerie.",
    translation: "the hotel owner",
  },
  {
    id: 26,
    word: "Une pelle",
    definition: "un objet qui sert à faire des trous dans le sol.",
    translation: "a shovel",
  },
  {
    id: 27,
    word: "Un ennemi",
    definition:
      "quelqu'un qui se bat contre quelqu'un d’autre et qui lui veut du mal.",
    translation: "an enemy",
  },
  {
    id: 28,
    word: "Il ne sait pas à qui il a affaire",
    definition: "il ne sait pas quel genre d'homme est en face de lui.",
    translation: "He doesn't know who he's dealing with",
  },
  {
    id: 29,
    word: "Nommer",
    definition: "dire le nom",
    translation: "to name",
  },
  {
    id: 30,
    word: "L'hôte",
    definition: "ici, l'hôtelier",
    translation: "the host",
  },
  {
    id: 31,
    word: "Gêner",
    definition: "déranger",
    translation: "to bother",
  },
  {
    id: 32,
    word: "Sans doute",
    definition: "ici, oui, sûrement",
    translation: "without a doubt",
  },
  {
    id: 33,
    word: "Faites mon compte",
    definition: "dites-moi combien je dois vous payer",
    translation: "calculate my bill",
  },
  {
    id: 34,
    word: "Un coup d'œil",
    definition: "un regard rapide mais qui veut dire beaucoup de choses",
    translation: "a glance",
  },
  {
    id: 35,
    word: "Chasser",
    definition: "ici, faire partir",
    translation: "to chase away",
  },
  {
    id: 36,
    word: "Arrêter quelqu'un",
    definition: "le mettre en prison",
    translation: "to arrest someone",
  },
  {
    id: 37,
    word: "Il le pousse à",
    definition: "il lui fait sentir qu’il doit faire quelque chose",
    translation: "He urges him to",
  },
  {
    id: 38,
    word: "Aveugle",
    definition: "qui ne peut pas voir",
    translation: "blind",
  },
  {
    id: 39,
    word: "Du linge",
    definition: "du tissu",
    translation: "laundry",
  },
  {
    id: 40,
    word: "La portière",
    definition: "la porte de la voiture",
    translation: "car door",
  },
  {
    id: 41,
    word: "Prévenir",
    definition: "dire à quelqu'un une chose avant qu'elle n'arrive",
    translation: "to warn",
  },
  {
    id: 42,
    word: "Misérable",
    definition: "méchant homme",
    translation: "miserable",
  },
  {
    id: 43,
    word: "L'hôtelier",
    definition:
      "maladie : l’hôtelier pense que d’Artagnan sera malade pendant onze jours et qu'il lui fera payer une pièce d’or par jour.",
    translation: "the innkeeper",
  },
  {
    id: 44,
    word: "Des produits",
    definition: "ici, des choses qui vont lui servir à faire le médicament",
    translation: "products",
  },
  {
    id: 45,
    word: "Elles manquent se rouvrir",
    definition: "elles vont presque s'ouvrir à nouveau",
    translation: "They are about to reopen",
  },
  {
    id: 46,
    word: "Plaindre",
    definition: "dire à quelqu'un qu'on n’est pas content",
    translation: "to complain",
  },
  {
    id: 47,
    word: "Bon marché",
    definition: "pas cher du tout",
    translation: "inexpensive",
  },
  {
    id: 48,
    word: "Coudre",
    definition: "arranger avec du fil et une aiguille",
    translation: "to sew",
  },
  {
    id: 49,
    word: "Déchirés",
    definition: "en morceaux",
    translation: "torn",
  },
  {
    id: 50,
    word: "Avoir de l'esprit",
    definition: "savoir faire rire de façon intelligente",
    translation: "to have wit",
  },
  {
    id: 51,
    word: "Une maison de jeu",
    definition:
      "un endroit où on joue aux cartes et à d'autres jeux pour de l'argent",
    translation: "a gambling house",
  },
  {
    id: 52,
    word: "Font sonner leurs épées",
    definition:
      "montrent qu'ils sont toujours prêts à se battre avec leurs épées",
    translation: "clang their swords",
  },
  {
    id: 53,
    word: "Il est aimé comme un dieu",
    definition: "il est très aimé",
    translation: "He is loved like a god",
  },
  {
    id: 54,
    word: "Une idée",
    definition: "une pensée, un concept",
    translation: "an idea",
  },
  {
    id: 55,
    word: "Le comte",
    definition: "un titre de noblesse",
    translation: "the count",
  },
  {
    id: 56,
    word: "Blesser",
    definition: "causer une blessure, faire mal",
    translation: "to injure",
  },
  {
    id: 57,
    word: "L'argent",
    definition:
      "la monnaie, les pièces et les billets utilisés pour acheter des choses",
    translation: "money",
  },
  {
    id: 58,
    word: "Le cheval",
    definition: "un animal utilisé pour le transport ou l'agriculture",
    translation: "the horse",
  },
  {
    id: 59,
    word: "Le voleur",
    definition:
      "une personne qui vole, qui prend les biens des autres sans permission",
    translation: "the thief",
  },
  {
    id: 60,
    word: "La forêt",
    definition: "un grand espace rempli d'arbres et de végétation",
    translation: "the forest",
  },
  {
    id: 61,
    word: "Le secret",
    definition:
      "quelque chose que l'on ne doit pas révéler ou partager avec d'autres",
    translation: "the secret",
  },
  {
    id: 62,
    word: "Le mystère",
    definition:
      "quelque chose d'inexpliqué, qui suscite de l'intérêt et de la curiosité",
    translation: "the mystery",
  },
  {
    id: 63,
    word: "La trahison",
    definition:
      "agir contre quelqu'un en ne respectant pas la confiance ou la loyauté",
    translation: "betrayal",
  },
  {
    id: 64,
    word: "Le danger",
    definition: "une situation potentiellement nuisible ou risquée",
    translation: "danger",
  },
  {
    id: 65,
    word: "Le combat",
    definition: "une lutte physique entre deux personnes ou groupes",
    translation: "the fight",
  },
  {
    id: 66,
    word: "La victoire",
    definition: "le résultat positif d'une compétition ou d'un conflit",
    translation: "victory",
  },
  {
    id: 67,
    word: "La défaite",
    definition: "le résultat négatif d'une compétition ou d'un conflit",
    translation: "defeat",
  },
  {
    id: 68,
    word: "La fuite",
    definition:
      "quitter rapidement un lieu pour échapper à un danger ou à une situation désagréable",
    translation: "escape",
  },
  {
    id: 69,
    word: "Le trésor",
    definition:
      "une collection de biens précieux, souvent cachés ou gardés en sécurité",
    translation: "treasure",
  },
  {
    id: 70,
    word: "La magie",
    definition:
      "l'utilisation de forces surnaturelles pour produire des effets mystérieux",
    translation: "magic",
  },
];
